### ISSUE TITLE
gem bump tags the wrong version

### ISSUE THREAD

**Issue by idoa01** [svenfuchs/gem-release#79]
Hi, I'm trying to use the gem like this: `gem bump --tag --skip-ci --push --version patch`
my current version is 0.0.1 and I'm bumping to 0.1.0
I'm expecting the tag to be set to 'v0.1.0' but instead I'm getting this output (and the tag created is the same):

```
bump my-gem 0.0.1 0.1.0
version lib/my-gem/version.rb 0.0.1 0.1.0
git_add lib/my-gem/version.rb
git_commit "Bump my-gem to 0.1.0 [skip ci]"
[master 128a501] Bump my-gem to 0.1.0 [skip ci]
 1 file changed, 1 insertion(+), 1 deletion(-)
git_push origin
tag my-gem 0.0.1
git_tag v0.0.1 v0.0.1
git_push origin
```

**Comment by taylorthurlow** [comment]
I'm also experiencing the same issue.

**Comment by PikachuEXE** [comment]
Opened #83 to fix this issue > 50%
Why not 100%? Read the PR :)

**Comment by PikachuEXE** [comment]
If no rejection I will release #83 next week Friday

**Comment by PikachuEXE** [comment]
Partial fix released as [`2.0.3`](https://rubygems.org/gems/gem-release/versions/2.0.3)

**Comment by bguest** [comment]
I'm still experiencing this issue with version 2.2.1 `gem bump patch`, `gem bump minor` and `gem bump patch` all do the same thing, bump the patch version: ie:
```
$ gem bump major                                                                                                                                                                                                                                                                                                                                                                           rbenv:2.6.2

Bumping my_gem from version 1.1.3 to 1.1.4
Changing version in lib/my_gem/version.rb from 1.1.3 to 1.1.4

All is good, thanks my friend.
```

**Comment by PikachuEXE** [comment]
@bguest 
I have reproduced your issue
Let me see why it works in spec...

**Comment by PikachuEXE** [comment]
@bguest 
Oh you need to use `--version` like
```
gem bump --version major
gem bump --version minor
```
See [`gem bump` doc](https://github.com/svenfuchs/gem-release#gem-bump)
